version: '3'

services:
  mockterview-backend:
    container_name: mockterview-backend-app
    image: mockterview-backend-prod:latest
    restart: always
    networks:
      - mockterview-backend
    environment:
      - ENV=prod
      - TZ=Asia/Seoul
  proxy:
    container_name: mockterview-nginx
    image: mockterview-nginx-prod:latest
    restart: always
    networks:
      - mockterview-backend
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx-prod.conf:/etc/nginx/nginx.conf
networks:
    mockterview-backend:
        external: true
